sudo: required
language: erlang
otp_release:
  - 23.0
  - 22.3
  - 21.3
before_install:
  - |
    docker run --rm \
               -v ${HOME}:${HOME} \
               -v /etc/passwd:/etc/passwd \
               -u $(id -u) \
               -w ${PWD} \
               -e PATH=${PATH} \
               silex/emacs:${EMACS} \
               emacs -Q --batch -l test_data/package-install-deps.el
services:
  - docker
env:
  - EMACS=24.5-dev
  - EMACS=25.3-dev
  - EMACS=26.3-dev
script:
  - |
    docker run --rm \
               -v ${HOME}:${HOME} \
               -v /etc/passwd:/etc/passwd \
               -u $(id -u) \
               -w ${PWD} \
               -e PATH=${PATH} \
               silex/emacs:${EMACS} \
               /bin/bash --norc -c 'make test'
